<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Company extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'symbol',
        'listing_date',
        'psei',
        'active'
    ];

    public function getRouteKeyName()
    {
        return 'symbol'; // TODO: Change the autogenerated stub
    }

    public function subsector()
    {
        return $this->belongsTo(Subsector::class);
    }

    public function prices()
    {
        return $this->hasMany(HistoricalPrice::class)
            ->orderBy('date','ASC');
    }

    public function latest_price(): HasOne
    {
        return $this->hasOne(HistoricalPrice::class)
            ->latestOfMany();
    }
}
